@startuml use_case_diagram
left to right direction

' skin parameters for usecase with special stereotype
skinparam usecase<<unspezifiziert>> {
  BackgroundColor #eee
  BorderColor #gray
  StereotypeFontColor #gray
  StereotypeFontSize 10
}

actor Präsentator


rectangle "Desktop Anwendung - E04_Effektive_Präsentation" {
  usecase "UC01\n Laden mehrerer Medien in das System " as uc01 
  usecase "UC02\n Speichern der Medien als Package auf einem mobilen Speicher " as uc02
  usecase "UC03\n geladene Medien auf fremeden System abspielen " as uc03
  usecase "UC04\n Einblenden \von Zusatzinformationen" as uc04

}

Präsentator -- uc01
Präsentator -- uc02
Präsentator -- uc03
uc03 .down.> uc04 : include

@enduml